name: Terraform Deployment to Grafana

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      # Install dependencies (if any)
      - name: Install dependencies
        run: terraform init

      # Run Terraform plan to check for changes
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform changes to Grafana
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GRAFANA_API_KEY: ${{ secrets.glsa_sqAdiGhYdt0JGpe51c2DpS5flhjpD41C_4732185b }}
